9481 pdf codebook
IQSS/dataverse pull request #10295
Opened 2024-02-02 22:12 UTC by lubitchv

**What this PR does / why we need it**:

**Which issue(s) this PR closes**:

Closes #

**Special notes for your reviewer**:

**Suggestions on how to test this**:

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:

**Is there a release notes update needed for this change?**:

**Additional documentation**:

2024-04-04 17:54 UTC, qqmyers commented
@lubitchv - have you been able to look at using the new external exporter mechanism for this? It would be nice to have a real exporter use it and that would allow v6.2 (v6.1?) instances to drop it in, but since you created this ~in parallel, I don't think we should hold this up if you'd rather this go forward as is (or if we need to see if anyone else is interested/able to make the changes to package it as an external exporter jar).

2024-04-04 18:00 UTC, lubitchv commented
No, I did not yet looked at the external exporters. If you could push this PR as it is it would be great. I do plan to look at the external exporters, just did not have time to do that.

2024-04-17 22:04 UTC, qqmyers commented
The current plan is to use the separate PR at https://github.com/gdcc/dataverse-exporters/pull/11 to produce an external jar for the ddi pdf exporter and to modify this PR to just include changes/docs required in the core repository. Changes TBD so this is waiting for changes before continuing through review/QA.

2024-06-07 19:04 UTC, pdurbin commented
@qqmyers is that still the plan? To use https://github.com/gdcc/dataverse-exporters ?

I'm asking because I prefer a separate repo, like I did for https://github.com/gdcc/exporter-croissant

Either way, this PR needs to be converted to "docs only", right? Should this be moved back to "in progress"?

2024-06-21 16:06 UTC, qqmyers requested changes
Code will go to https://github.com/gdcc/exporter-ddipdf. This PR will just be the api change.

2024-06-21 16:11 UTC, lubitchv commented on src/main/java/edu/harvard/iq/dataverse/export/PdfCodeBookExporter.java
> +        return MediaType.WILDCARD;
I tried pdf, it does not seem to work and the only thing that worked was WILDCARD

2024-06-21 16:19 UTC, lubitchv commented on src/main/resources/edu/harvard/iq/dataverse/ddi-pdf/i18n.inc.xsl
> +	<xsl:param name="language-code" select="'en'"/>
Yes, it is always using English in this case. I do not know how to sent to xsl, that is why I were asking you about the language.

2024-06-21 16:21 UTC, lubitchv commented on src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
> +    @Produces({"application/xml", "application/json", "application/html", "*/*" })
Yes, I think "*/*" can be added after "application/ld+json"

2024-06-21 16:29 UTC, lubitchv commented on src/main/java/edu/harvard/iq/dataverse/export/PdfCodeBookExporter.java
> +        return "pdf";
I think it has to correspond to the name in the api call for exporters and in UI page call for the exporter, in other words it is a name of the exporter that is used in calls of the exporter

2024-06-21 17:01 UTC, qqmyers commented on src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
> +    @Produces({"application/xml", "application/json", "application/html", "*/*" })
@lubitchv - great - if you can make this change and delete the rest of the changes, this can go forward.

2024-06-25 15:59 UTC, qqmyers approved these changes
Coordinating w/ @lubitchv and @poikilotherm, the ddipdf previewer is now in https://github.com/gdcc/exporter-ddipdf and this PR is just a one line change to add "*.*" to the list of possible mimetypes exporters can produce, which is a general improvement to support external exporters.

For QA, probably regression testing is all that's needed, although on could check the open api output (assuming that includes allowed mimetpyes).

2024-06-27 14:14 UTC, merged