Add API endpoint for comparing Dataset Versions
IQSS/dataverse pull request #10945
Opened 2024-10-21 15:19 UTC by stevenwinship

**What this PR does / why we need it**: Need an API endpoint that will compare two dataset versions and return a list of differences between the versions. This is needed to support the SPA Dataset Page

**Which issue(s) this PR closes**: https://github.com/IQSS/dataverse/issues/10888

- Closes #10888

**Special notes for your reviewer**:

**Suggestions on how to test this**: See IT and Unit tests

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**: New API

**Is there a release notes update needed for this change?**: Included

**Additional documentation**:

2024-10-24 15:41 UTC, stevenwinship commented
> HI @stevenwinship I tried the latest version of the API, it looks good, just needs a few small changes:
> 
> * oldVersion: use 'lastUpdatedDate' rather than 'createdDate'
> * files: (added, removed or replaced):  include tags (categories) and filePath (directoryLabel)

Fixed

2024-10-25 20:16 UTC, pdurbin commented
There's potential for merge conflicts with this PR:

- #10969

Right? 🤔

2024-10-28 09:26 UTC, luddaniel commented
> There's potential for merge conflicts with this PR:
> 
> * [Ordering subfields while displaying dataset version differences #10969](https://github.com/IQSS/dataverse/pull/10969)
> 
> Right? 🤔

I think it's conflict-free. Maybe in IT tests. I will help if needed.
Good job @stevenwinship by the way.

2024-11-05 15:05 UTC, sekmiller commented on doc/sphinx-guides/source/api/native-api.rst
> +
You should say that you need to provide an api token with view unpublished privileges to compare draft version

2024-11-05 15:20 UTC, sekmiller commented on src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
> +            return ok(DatasetVersion.compareVersions(dsv1, dsv2));
Should there be a test to make sure that the versions are considered in the correct order?

2024-11-05 20:40 UTC, sekmiller requested changes
This looks very good. Just a couple of minor nits and a reminder to bring the branch up to date with Dev. Thanks

2024-11-06 17:56 UTC, sekmiller approved these changes
Thanks for the updates. approved

2024-11-22 16:46 UTC, merged