expose links to all export formats via Signposting
IQSS/dataverse pull request #11045
Opened 2024-11-22 18:27 UTC by pdurbin

**What this PR does / why we need it**:

**Which issue(s) this PR closes**:

- Closes #10542

**Special notes for your reviewer**:

**Suggestions on how to test this**:

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:

**Is there a release notes update needed for this change?**:

**Additional documentation**:

2024-11-22 23:54 UTC, qqmyers requested changes
Looks good. Nice to have all our formats in Signposting - we should make sure Herbert vdS knows. I suggested on change to avoid problems with permalinks.

2024-11-22 23:54 UTC, qqmyers commented on src/main/java/edu/harvard/iq/dataverse/util/SignpostingResources.java
> +                        + ds.getProtocol() + ":" + ds.getAuthority() + "/" + ds.getIdentifier() + ">;rel=\"describedby\"" + ";type=\"" + exporter.getMediaType() + "\"";
These (this and line 137) are broken for permalinks which don't necessarily have / as a separator.  I think you can just ds.getGlobalId().asString() instead. For a real dataset, I don't think you can ever have a null GlobalId so not sure you even need to check for that.

2024-11-25 15:55 UTC, pdurbin commented
Whoops, tests are failing. https://jenkins.dataverse.org/blue/organizations/jenkins/IQSS-Dataverse-Develop-PR/detail/PR-11045/3/tests

I'll take a look.

2024-11-25 17:29 UTC, pdurbin commented
I pushed some commits to fix the broken tests, update the API changelog and release note, and fix a broken header in the docs.

This test was failing in Jenkins: `mvn test -Dtest=FilesIT#testDeleteFile`. I ran it locally and it seems fine. I think it's unrelated to this PR. Here's the failure...

```
JSON path data.files[0].dataFile.filename doesn't match.
Expected: cc0.png
  Actual: orcid_16x16.png
```

... on this line: https://github.com/IQSS/dataverse/blob/f95c1a0366d38119e6e235fccce1d91af936b84d/src/test/java/edu/harvard/iq/dataverse/api/FilesIT.java#L2278

Again, I don't think it has anything to do with changes in the PR but I'm just mentioning it in case we start seeing it elsewhere.

@qqmyers if you would take another look I'd appreciate it!

2024-11-25 17:31 UTC, pdurbin commented
By the way, @4tikhonov pointed out to me that Dataverse shows up in this report of who has implemented Signposting: https://s11.no/2024/signposting-report/

2025-01-03 19:31 UTC, ofahimIQSS commented
branch has conflicts, can you please resolve?

2025-01-07 19:26 UTC, pdurbin commented
@ofahimIQSS yes, done in 76c347b

2025-01-13 19:56 UTC, pdurbin commented
As discussed at a couple standups and [in Slack](https://iqss.slack.com/archives/C03R1E7T4KA/p1736527734534289), I pulled this PR out of "ready for QA" in order to think about the JSON-LD "profile" parameter I learned about last week in a presentation by @stain about Signposting to the Croissant working group.

As of this writing, "profile" information is not present. For Croissant, for example, The following should appear in the Signposting output:

`<https://demo.dataverse.org/api/datasets/export?exporter=croissant&persistentId=doi:10.5072/FK2/YD5QDG>;rel="describedby";type="application/json"`

In the future, we plan to establish a pattern where exporters can put "profile" information in their `getMediaType()` method. I created a new issue to track that work:

- #11151

I've already created https://github.com/gdcc/exporter-croissant/pull/7 to update the Croissant exporter such that once it has been merged a new version has been released, we should expect to see Signposting output like this for Croissant:

`<https://demo.dataverse.org/api/datasets/export?exporter=croissant&persistentId=doi:10.5072/FK2/YD5QDG>;rel="describedby";type="application/ld+json"; profile="http://mlcommons.org/croissant/1.0"`

(Yes, in that PR we are also making the type more specific by changing `json` to `ld+json`.)

Likewise, I've made a PR for the RO-Crate exporter at https://github.com/gdcc/exporter-ro-crate/pull/4 to add the "profile" information.

Now that we have #11151 to track future work, I don't see any reason to hold up this PR (#11045), so I'm moving it back to "ready for QA".

2025-02-05 21:40 UTC, ofahimIQSS commented
Tests are passing, performed testing functional and regression testing on internal - no issues uncovered. Merging PR

HEAD request:
curl -I https://dataverse-internal.iq.harvard.edu/dataset.xhtml?persistentId=doi:10.70122/FK2/M5WCHB
![image](https://github.com/user-attachments/assets/f479a678-67b9-40cf-9fc8-956522ae2fb5)

GET request:
curl -i https://dataverse-internal.iq.harvard.edu/dataset.xhtml?persistentId=doi:10.70122/FK2/M5WCHB
![image](https://github.com/user-attachments/assets/960951c6-26dc-45a0-91ae-2a2dff026b3c)

API
curl -H "Accept:application/json" "https://dataverse-internal.iq.harvard.edu/api/datasets/:persistentId/versions/1.0/linkset?persistentId=doi:10.70122/FK2/M5WCHB" |jq
![image](https://github.com/user-attachments/assets/b234a70b-494d-44f3-9f01-a0861a46feda)

2025-02-05 21:41 UTC, merged