Globus support: download optimizations
IQSS/dataverse pull request #11125
Opened 2024-12-30 02:57 UTC by landreev

**What this PR does / why we need it**:

This is a draft! 

**Which issue(s) this PR closes**:

- Closes #11057

**Special notes for your reviewer**:

**Suggestions on how to test this**:

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:

**Is there a release notes update needed for this change?**:

**Additional documentation**:

2025-02-25 19:41 UTC, qqmyers commented on src/main/webapp/filesFragment.xhtml
> +                                             and DatasetPage.isShowQueryButton(fileMetadata.dataFile.id)
isShowQueryButton handles all of these (and retention period) except for tabularData, which is at least partially handled by registering for specific mime types. (Is the concern that it shows when ingests fails? (Does the Ask the Data' tool fail if ingest fails or can it do something with just the file?).
Whatever the correct logic - perhaps any changes can just go in isShowQueryButton() ?

2025-02-25 19:42 UTC, qqmyers commented on src/main/java/edu/harvard/iq/dataverse/globus/TaskMonitoringServiceBean.java
> +            String globusClientToken = getClientTokenForStorageDriver(t.getDataset(), false);
Not a big deal, but this section is common to up and download.

2025-02-25 19:43 UTC, stevenwinship requested changes

2025-02-25 19:43 UTC, stevenwinship commented on src/main/java/edu/harvard/iq/dataverse/globus/GlobusServiceBean.java
> +                Thread.sleep(3000);
you should only sleep if the taskState == null and there are no more retries. This will delay the loop process an extra 3 seconds every time for no reason.

2025-02-25 19:43 UTC, stevenwinship commented on src/main/java/edu/harvard/iq/dataverse/globus/GlobusServiceBean.java
> +            // another attempt to look it up later
I'm not crazy about code blocks with no actual code but ok. Maybe add a logger.fine saying the rule was not found?

2025-02-25 19:43 UTC, stevenwinship commented on src/main/java/edu/harvard/iq/dataverse/globus/GlobusServiceBean.java
> +            } catch (InterruptedException ie) {
Same as above. This is an extra 3 second delay after the taskState is found.

2025-02-25 19:51 UTC, qqmyers commented on src/main/java/edu/harvard/iq/dataverse/globus/GlobusServiceBean.java
> +                requestPermStatus = 201;
Should this get logged? Something went wrong with a prior removal (which doesn't have to stop this request but shouldn't be ignored as it's a bug/problem if perms aren't going away)

2025-02-25 19:55 UTC, qqmyers commented on src/main/java/edu/harvard/iq/dataverse/globus/GlobusServiceBean.java
> +            if (FeatureFlags.GLOBUS_USE_EXPERIMENTAL_ASYNC_FRAMEWORK.enabled()) {
So unlike the upload case, this is still failing if Dataverse failed to delete it after the last download? It's only allowing multiple parallel downloads. (So no reason to log here as this is valid versus evidence of some problem).

2025-02-25 20:18 UTC, qqmyers reviewed
Looks good - I suggested a couple minor changes but I think the overall logic in the updates make sense.

2025-02-25 20:32 UTC, landreev commented on src/main/java/edu/harvard/iq/dataverse/globus/GlobusServiceBean.java
> +                Thread.sleep(3000);
Correct, will fix.

2025-02-25 20:54 UTC, landreev commented on src/main/java/edu/harvard/iq/dataverse/globus/GlobusServiceBean.java
> +            if (FeatureFlags.GLOBUS_USE_EXPERIMENTAL_ASYNC_FRAMEWORK.enabled()) {
With this change it is NOT failing if the rule is already there (whether because Dataverse failed to delete it after a past download; or because it was created for a download that's still running) and the new monitoring mode is in use.

It is these extra lines above that actually make it possible to have multiple downloads from the same dataset. Prior to this pr, Dataverse would try to request an access rule, get back a 409, and pass it to the app; which in turn would tell the user that "download could not be started". Now the code intercepts the 409, verifies that the "r" permission for this user/this folder does exist, then returns 201, and the app proceeds to initiate the download. On the completion of the task, the monitoring service code checks if there are still any other tasks in the database-stored queue using the same rule, and only deletes it if there are none.

2025-02-25 21:06 UTC, qqmyers commented on src/main/java/edu/harvard/iq/dataverse/globus/GlobusServiceBean.java
> +            if (FeatureFlags.GLOBUS_USE_EXPERIMENTAL_ASYNC_FRAMEWORK.enabled()) {
Got it. So a) why the check for the feature flag for download and not upload? and b) can you distinguish between parallel downloads and a prior failure (would the ruleId be in the cache for multiple downloads but not for a failed delete?)? As with the upload case, I'm worried that problems that leave a permission in place will get ignored because they now don't stop a new request and there's no logging.

2025-02-25 21:32 UTC, landreev commented on src/main/webapp/filesFragment.xhtml
> +                                             and DatasetPage.isShowQueryButton(fileMetadata.dataFile.id)
Funny thing you noticed this... I put together these logic modes in response to something you pointed out to me a few releases back - namely that the rendering logic for this button introduced an ungodly number of datafileservice.find() calls (it's a case of  x7 jsf renderings); the whole thing was added to a release at the last minute, AND after I had gone to some trouble reducing the number of database lookups in the page. The above did not completely fix it, but at least reduced the lookups, by narrowing when the method is called to tabular, released, ... etc. files (the tool is only supposed to run on public tab. files, etc. - the logic is inside the method; unfortunately, it's only applied there after the db. lookups). So, I added these bandaid lines to the custom changes I deploy in prod. at iqss... and forgot about it/never made a real pr. These changes made it back into this branch kind of by accident; but when I noticed I figured this would be a good opportunity to check it in. 

Ideally, that method should not be called on the db id of the filemetadata in the first place; the page has access to actual entities. The main reason I never bothered with a cleaner fix was that it felt wrong to invest any work into jsf; since it was allegedly going awy any sec. 

Was a longer explanation than the issue is worth, for sure...

2025-02-25 22:11 UTC, landreev commented on src/main/java/edu/harvard/iq/dataverse/globus/GlobusServiceBean.java
> +            if (FeatureFlags.GLOBUS_USE_EXPERIMENTAL_ASYNC_FRAMEWORK.enabled()) {
a) For downloads: if the old-style continuous task monitoring is used, the code is falling back to the old behavior; under the assumption that there may be another active task using the rule, and then it would be impossible to prevent the one that finishes first from deleting the rule and killing the other task(s). 
I'm not doing that for uploads, under the assumption that it is impossible to start more than one - since the dataset gets locked. So, if we found an existing  rule, it must be from a finished or failed task. 
I agree that this needs to be logged; and I should probably add a warning to the guide somewhere to keep an eye for these warnings. 
b) I haven't been able to come up with a way to distinguish between a stale vs. still in use rule, without the database record. I don't think we can rely on the cache for this. We do remove the rule from the cache when we start transfers; that can be modified somehow, but then we are back to relying on the server staying up (we now have real-life cases of downloads, and occasional uploads that take days); plus the issue of multiple servers at IQSS and possibly other places. 

BTW, do you know/remember why the rules Dataverse creates have no expiration dates? - making them expire/disappear eventually on their own would help, I think. 

c) I'm realizing we need a dedicated admin api call for clearing up stale access rules. I've been doing that outside of Dataverse, but it would be trivial to add. Again, I'll only be able to tell for sure if it's stale or not with the db tracking on. But then this is something I'll likely feel comfortable dropping the "experimental" label from and making the default behavior in 6.7.

2025-02-25 22:14 UTC, landreev commented on src/main/webapp/filesFragment.xhtml
> +                                             and DatasetPage.isShowQueryButton(fileMetadata.dataFile.id)
(if I have a sec, I'll go ahead and rewrite the `DatasetPage.isShowQueryButton()` method to be less of a hog, now that I had to remember the whole thing in vivid detail)

2025-02-25 22:43 UTC, qqmyers commented on src/main/java/edu/harvard/iq/dataverse/globus/GlobusServiceBean.java
> +            if (FeatureFlags.GLOBUS_USE_EXPERIMENTAL_ASYNC_FRAMEWORK.enabled()) {
re: expiration - I don't know why we don't use them - perhaps no one saw that option? Or it's hard to predict how long you need? Seems like some conservative passive expiration would make sense though.

2025-02-25 22:48 UTC, qqmyers commented on src/main/webapp/filesFragment.xhtml
> +                                             and DatasetPage.isShowQueryButton(fileMetadata.dataFile.id)
Hmm - is that because we use the file id and then look it up in that method? Could we make it use the Datafile as a param and avoid the lookups and keep it all in the java code?

2025-02-26 14:22 UTC, landreev commented on src/main/webapp/filesFragment.xhtml
> +                                             and DatasetPage.isShowQueryButton(fileMetadata.dataFile.id)
That's what I was trying to say last night, yes; that's how it should've been implemented in the first place. 
The conversation in question happened 1.5 yrs ago, right after 5.14, apparently: 
<img width="669" alt="Screen Shot 2025-02-26 at 9 00 08 AM" src="https://github.com/user-attachments/assets/e411fe5c-b434-49fc-aaa1-6939a2d927c6" />
<img width="674" alt="Screen Shot 2025-02-26 at 9 02 46 AM" src="https://github.com/user-attachments/assets/e4336fe1-f266-4423-a556-dae9175a2b38" />

2025-02-26 14:32 UTC, landreev commented on src/main/java/edu/harvard/iq/dataverse/globus/GlobusServiceBean.java
> +                Thread.sleep(3000);
We actually want to have a short sleep there before making that first call; so I rearranged the order/got rid of some extra sleep lines outside of that block.
The redundant sleep lines there we a bit messy. But actual extra  sleep time doesn't hurt anything there since the methods are executed in the background, via the `@Asynchronous` annotation.

2025-02-26 15:49 UTC, landreev commented on src/main/webapp/filesFragment.xhtml
> +                                             and DatasetPage.isShowQueryButton(fileMetadata.dataFile.id)
There was also this in the same thread: 

<img width="1025" alt="Screen Shot 2025-02-26 at 10 48 13 AM" src="https://github.com/user-attachments/assets/63ca66f9-86d4-4d97-b914-acff2444a3f4" />

... might as well, at this point.

2025-02-27 14:34 UTC, landreev commented on src/main/webapp/filesFragment.xhtml
> +                                             and DatasetPage.isShowQueryButton(fileMetadata.dataFile.id)
I added a sentence to "how to test" explaining that QA should include checking on the previewers and tools before and after.

2025-03-03 16:12 UTC, stevenwinship approved these changes

2025-03-05 21:58 UTC, ofahimIQSS commented
Getting internal server error when I push PR to internal:

2025-03-05 22:06 UTC, qqmyers commented
Looks like the error is not related to the PR - a consequence of testing #11068 first which drops a datasetversion column.

2025-03-06 15:06 UTC, ofahimIQSS commented
Currently there is an issue holding this up for testing:
https://github.com/IQSS/dataverse/pull/11282#issuecomment-2704078292

2025-03-06 17:35 UTC, ofahimIQSS commented
@landreev How would I get past this?:

https://github.com/user-attachments/assets/0abf4437-7d2f-46db-aca2-84bf3e46780c

2025-03-06 19:33 UTC, ofahimIQSS commented
Testing Evidences:

![image](https://github.com/user-attachments/assets/6e713112-9332-4a7f-b054-5312c6355c36)
![image](https://github.com/user-attachments/assets/5134f3e6-2328-4404-9e17-e4eef5162719)

Parallel Upload successful with large files:
![image](https://github.com/user-attachments/assets/abc18f8c-f794-43a5-9e7d-823e5acf5e58)
![image](https://github.com/user-attachments/assets/6c2597f6-04de-4826-8943-ac1db1a4a306)

2025-03-06 19:36 UTC, ofahimIQSS commented
Maybe not related to the PR but here is an observation I made:
When there are too many ineligible files selected on a Globus download, the message box doesn't allow user to scroll down. 

https://github.com/user-attachments/assets/5429ba1d-7461-49a7-8f12-7ef6da31528b

2025-03-07 19:47 UTC, ofahimIQSS commented
> Maybe not related to the PR but here is an observation I made: When there are too many ineligible files selected on a Globus download, the message box doesn't allow user to scroll down and hit continue button.

A separate PR has been opened to track this. Merging PR.

2025-03-07 19:47 UTC, merged

2025-03-07 21:26 UTC, landreev commented
Thank you for merging the PR and for the detailed report! 
Sorry for the delay, I just got around to looking into this. 
(remember - I am, technically, off today 🥲) 
Special thanks to @qqmyers for the assistance with testing. 

Opening the new issue was the right thing to do, that's what I would have recommended myself. I'll add a comment there.