dirindex doc should show use of DOI for end users
IQSS/dataverse pull request #7800
Opened 2021-04-14 11:29 UTC by mankoff

Minor doc edit to show end-users how they can use new `dirindex` API using **DOI** rather than dataset **ID**.

2021-04-14 16:22 UTC, pdurbin reviewed
@mankoff overall, looks great! I made a couple suggestions.

2021-04-14 16:22 UTC, pdurbin commented on doc/sphinx-guides/source/api/native-api.rst
> +  curl ${SERVER_URL}/api/datasets/:persistentId/dirindex/?persistentId=doi:${PERSISTENT_ID}
```suggestion
  curl ${SERVER_URL}/api/datasets/:persistentId/dirindex?persistentId=doi:${PERSISTENT_ID}
```

(We're trying to get away from these trailing slashes.)

2021-04-14 16:22 UTC, pdurbin commented on doc/sphinx-guides/source/api/native-api.rst
> +  wget -r -e robots=off -nH --cut-dirs=3 --content-disposition https://demo.dataverse.org/api/datasets/:persistentId/dirindex/?persistentId=doi:${PERSISTEN_DOI}
```suggestion
  wget -r -e robots=off -nH --cut-dirs=3 --content-disposition https://demo.dataverse.org/api/datasets/:persistentId/dirindex?persistentId=doi:${PERSISTENT_ID}
```

2021-04-14 16:35 UTC, mankoff commented
I committed the suggested changes.

2021-04-14 16:38 UTC, scolapasta requested changes

2021-04-14 16:38 UTC, scolapasta commented on doc/sphinx-guides/source/api/native-api.rst
> +  wget -r -e robots=off -nH --cut-dirs=3 --content-disposition https://demo.dataverse.org/api/datasets/:persistentId/dirindex?persistentId=doi:${PERSISTENT_ID}
One example shows a specific id, the other shows as a variable; they should at least be consistent

2021-04-22 16:07 UTC, scolapasta commented
@mankoff or @pdurbin  did you see the change request made? It should be small, and we can approve once it's consistent.

2021-04-22 18:30 UTC, mankoff reviewed
`24` changed to `${ID}` as per request.

2021-04-22 18:52 UTC, scolapasta approved these changes

2021-04-23 14:44 UTC, merged