S3: close DownloadInstanceWriter instream
IQSS/dataverse pull request #7914
Opened 2021-05-28 17:27 UTC by donsizemore

**What this PR does / why we need it**: see https://github.com/IQSS/dataverse/issues/7803#issuecomment-847344123

**Which issue(s) this PR closes**:

Closes #7910 

**Special notes for your reviewer**: this commit is best viewed with `&w=1`: https://github.com/IQSS/dataverse/compare/develop...OdumInstitute:7910_S3_close_inputstream?diff=split&w=1

**Suggestions on how to test this**: follow scenario described in https://github.com/IQSS/dataverse/issues/7803#issuecomment-847344123

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**: no

**Is there a release notes update needed for this change?**: no

**Additional documentation**: no

2021-05-28 18:44 UTC, qqmyers requested changes
Don - looks good - can you make it a three-line change instead (see comment)? With that, I think this is good to go.

2021-05-28 18:44 UTC, qqmyers commented on src/main/java/edu/harvard/iq/dataverse/api/DownloadInstanceWriter.java
> +                try (InputStream instream = storageIO.getInputStream()) {
Looks good to me. try-with-resources is the preferred way to assure streams are closed these days and that's what the PR does.

2021-05-28 18:44 UTC, qqmyers commented on src/main/java/edu/harvard/iq/dataverse/api/DownloadInstanceWriter.java
> +                        instream.close();
I guess this line is now redundant and could be removed.

2021-05-28 19:37 UTC, qqmyers approved these changes
The test @pdurbin saw fail appears to have succeeded in the new run. I can't see any reason the original commit would have caused a problem or why the second would fix it, so I'm guessing the test issue is some intermittent/unrelated issue.

2021-06-07 16:39 UTC, scolapasta approved these changes

2021-06-28 18:24 UTC, merged