Account migration
IQSS/dataverse pull request #7916
Opened 2021-05-31 16:02 UTC by janvanmansum

**What this PR does / why we need it**: Currently, when a user logs in to a migrated builtin user account for which the password is encrypted with a legacy hash algorithm (e.g., SHA-1), Dataverse will display a password reset page that also requires the user to accept the Terms of Use again. After a new password is provided it gets encrypted with the latest and greatest algorithm.

There are several limitations and issues with the current reset page:
* The introductory message talks about an upgrade from Dataverse 4.0, which is not necessarily the case.
* There is no way to only re-encrypt the current user password, i.e. the user is forced to provide a new one. However, for example DANS would like to just require the user to accept the Terms of Use again and no change the password.

Example of the current screen:
![image](https://user-images.githubusercontent.com/3862694/120212984-fe90fc00-c232-11eb-9e13-0cfc115100c5.png)

**Which issue(s) this PR closes**: N/A

**Special notes for your reviewer**: This PR introduces the following database settings:
* `:SilentPasswordAlgorithmUpdateEnabled`: if set to `true` with a `PUT` request, the "New Password" and "Retype Password" entry fields are hidden and the existing password is automatically re-encrypted on clicking the continue button.
* `:PVCustomPasswordResetAlertMessage`: the text that should appear in the blue banner at the top of the passwordreset page. 
* `:CustomPasswordResetButton`: the caption of the button to continue. (If `:SilentPasswordAlgorithmUpdateEnabled` is enabled you should override the default text which is "Reset Password".)
* `:CustomPasswordResetAlertIntro`: the introductory text.

Note that, if the password turns out, not to comply with the minimal security requirements, the user is presented with the regular password reset page on clicking Continue, and will be required to provide a new password.

**Suggestions on how to test this**:

1. Configure the Dataverse instance to automatically reencrypt password, e.g.:
   ```bash
    curl -X PUT -d "true" http://localhost:8080/api/admin/settings/:SilentPasswordAlgorithmUpdateEnabled
    curl -X PUT -d '{0} Our Terms of Use have been updated:{1} Please check the box below and click Continue' \
         http://localhost:8080/api/admin/settings/:PVCustomPasswordResetAlertMessage
    curl -X PUT -d "Continue" http://localhost:8080/api/admin/settings/:CustomPasswordResetButton
    curl -X PUT -d 'Please accept our new Terms of Use.  Also, note that you can connect your account to your institutional account, or ORCID, Google or GitHub account. To do so, log out after completing this step. Log in again with one of “Log in with our institutional account”, “ORCID”, “Google” or “GitHub”. ' http://localhost:8080/api/admin/settings/:CustomPasswordResetAlertIntro
    ```
2. Create a SHA-1 password, e.g.,  `echo -n mypassword001 | openssl dgst -binary -sha1 | openssl base64` 
3. Update the `builtinuser` table: 
    ```sql
    UPDATE builtinuser 
    SET encryptedpassword = '<result of previous command>'
    WHERE username = '<user to edit>';

    UPDATE builtinuser 
    SET passwordencryptionversion = 0
    WHERE username = '<user to edit>';
    ```
4. Log in. You should see a page similar to the one below:
    ![image](https://user-images.githubusercontent.com/3862694/120214948-73fdcc00-c235-11eb-87bf-3d4dbf577eb2.png)

(Note: you can customize the build number with the script `dataverse/scripts/custom-build-number` in the Dataverse code.)

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**: See previous item.

**Is there a release notes update needed for this change?**: No

**Additional documentation**:

2021-06-07 20:59 UTC, djbrooke commented
Hi @janvanmansum, thanks for sharing this. I appreciate the simplification of the workflow here. 

Just so I understand, when the user encounters this screen in the new Dataverse installation, will their passwords have already been loaded into the Dataverse installation's database? Would this only be able to be used by installations where passwords from the old system were known and transferred?

Regarding the 4.0 text, I've adjusted the text on a currently-unmerged branch so that the old version is not referenced specifically.

2021-06-22 13:31 UTC, djbrooke commented
Hi @janvanmansum, good to see you at the community meeting last week. I'm just making sure you saw my note above. Any thoughts?

2021-07-25 10:46 UTC, janvanmansum commented
@djbrooke : sorry for the late response. Yes, this assumes that the user password is in the database already (just not encrypted with the preferred algorithm).

2021-08-09 20:36 UTC, pdurbin commented
@janvanmansum hi, I'm just checking if this pull request is ready for review or if you're still working on it. I noticed a new commit from a couple weeks ago.

2021-08-11 15:41 UTC, djbrooke commented
Thanks @qqmyers for discussing, and thanks @janvanmansum for following up. I think we both missed each other a few times. :) 

I want @scolapasta to weigh in before we decide the merge this because we talked in some detail (prompting my question above in https://github.com/IQSS/dataverse/pull/7916#issuecomment-856253074) - if there's a specific security concern about implementing this, let's discuss.

2021-08-30 21:58 UTC, scolapasta commented
Hi, sorry for the delay in getting to this! I think the idea makes sense overall, but I wonder about having these settings? i.e. when we first added this we knew that we were requiring stricter passwords which was one reason to force the new password. But since this incorporates that (i.e. it forces new password if not strict enough), let's just make this the default behavior. In that way we can save a few settings and have all installations operate this way.

In short, rather than have this provide an alternative approach, let's have that alternative be standard.

@janvanmansum would you be able to make these changes?

2021-09-10 16:10 UTC, janvanmansum commented
@scolapasta : OK, then we will remove the settings and make the behavior the same as currently with the following values:

* SilentPasswordAlgorithmUpdateEnabled = true
* PVCustomPasswordResetAlertMessage = "Please, accept the new terms of use before continuing"
* CustomPasswordResetButton = "Continue"
* CustomPasswordResetAlertIntro = "Our terms of use have changed, please check the box below and click Continue"

2021-09-16 13:07 UTC, janvanmansum commented
@scolapasta : @mderuijter made the requested changes. Please, have another look at it. Thanks!

2021-09-16 15:12 UTC, djbrooke commented
Thanks @janvanmansum, we'll take another look!

2021-09-20 20:01 UTC, scolapasta requested changes

2021-09-20 20:01 UTC, scolapasta commented on src/main/java/edu/harvard/iq/dataverse/LoginPage.java
> +        FacesContext.getCurrentInstance().getExternalContext().getFlash().put("silentUpgradePasswd",authReq.getCredential(BuiltinAuthenticationProvider.KEY_PASSWORD));
what exactly are we passing here via flash? Is it the password (encrypted or not, should we have any concerns about security here?)

tagging @qqmyers also to see his thoughts

2021-09-20 20:53 UTC, qqmyers commented on src/main/java/edu/harvard/iq/dataverse/LoginPage.java
> +        FacesContext.getCurrentInstance().getExternalContext().getFlash().put("silentUpgradePasswd",authReq.getCredential(BuiltinAuthenticationProvider.KEY_PASSWORD));
As far as I know, flash is like a session in that the value isn't sent to the browser (unless you use the variable in the display somewhere - that is done here but to a password field which blanks the display.) And the value only stays around for one redirect (so better than a session).

I think returning the password to the reset page could be done, but I'm not sure there's much benefit and we'd lose things like the validation against current password rules that is triggered now (same as if the user types a new password). (Basically if you can see the password in the reset page https transmission, you could have gotten it when the user entered it on the login page.)

One suggestion I would make is to at least not set it unless the redirect to password reset will happen, line 212 below if I'm read code correctly. It wouldn't be used in other cases, but no need to set it either.

2021-09-21 09:45 UTC, mderuijter commented on src/main/java/edu/harvard/iq/dataverse/LoginPage.java
> +        FacesContext.getCurrentInstance().getExternalContext().getFlash().put("silentUpgradePasswd",authReq.getCredential(BuiltinAuthenticationProvider.KEY_PASSWORD));
@janvanmansum and I tested the flash variable to see if it remained in the FacesContext after a redirect. But as soon as the `newPassword` variable was set in `PasswordResetPage.java` line 106, the value was gone. I've implemented @qqmyers last suggestion so that the password only gets set when that redirect really happens, making the risk of exploitation even lower I think.

2021-09-24 21:07 UTC, scolapasta approved these changes
Looks good - thanks for the PR!

2021-09-27 13:31 UTC, djbrooke commented
@scolapasta @janvanmansum I'll move this back to review until we can take a look at the test failures. I can't access Jenkins right now, but as soon as I can I'll add the information here.

2021-09-27 15:58 UTC, djbrooke commented
(rerunning tests now)

2021-09-27 20:25 UTC, djbrooke commented
@janvanmansum Can you update from develop to capture the fixed tests? Once those run successfully we can move this to QA. Thank you!

2021-09-28 09:27 UTC, janvanmansum commented
Done by @mderuijter , merged to PR branch by me.

2021-09-28 13:19 UTC, djbrooke commented
Great, thanks @janvanmansum and @mderuijter. Tests pass!

2021-09-30 15:14 UTC, pdurbin requested changes
It looks like :PVCustomPasswordResetAlertMessage has been removed from the code but not the guides. At the very least, it should be removed from the guides and a release note should be added saying that the setting was removed.

2021-09-30 15:45 UTC, scolapasta commented
Actually before removing :PVCustomPasswordResetAlertMessage from the guide - it seems there may have been some confusion?

This setting existed before this PR and was not added here. The request I made during review was for removing the new settings you added. The confusion, I think is that in the initial comment this setting was listed under the "This PR introduces the following database settings", so seemed like it was also new and maybe why you remove dit?

However, @pdurbin looked and it seems as if it was actually added in: https://github.com/IQSS/dataverse/pull/4128

So the question I guess should be, should this one setting be left alone and not removed since it predates this PR and arguebly has a use outside of this PR? Or does this PR also remove the need for it (and if so, it should be removed from the guides?

@janvanmansum @mderuijter Could you review and let us know your thoughts? Thanks!

2021-10-01 12:40 UTC, janvanmansum commented
@scolapasta : you are right, `:PVCustomPasswordResetAlertMessage` was never part of this PR, so I have restored it now.

@pdurbin @mderuijter

2021-10-01 18:42 UTC, kcondon commented
@janvanmansum Thanks for the update. I think @scolapasta still needs to review but I decided to do a quick test of the password complexity workflow. It appears it is not functioning correctly in your branch at the moment. What happens is if I change :PVMinLength to be 10 rather than 6 and log in with an existing account, without setting :PVCustomPasswordResetAlertMessage, I see different results:

On develop branch, I see this:
<img width="1008" alt="Screen Shot 2021-10-01 at 2 29 13 PM" src="https://user-images.githubusercontent.com/4983816/135669890-dcfcd17c-e2eb-42e4-a375-c65636ddb0e8.png">

On your account migration branch, I see this:
<img width="1253" alt="Screen Shot 2021-10-01 at 2 41 37 PM" src="https://user-images.githubusercontent.com/4983816/135670975-98d13c14-a93a-466c-98bb-1acd510b8a86.png">

2021-11-04 21:52 UTC, scolapasta approved these changes

2021-11-08 20:50 UTC, scolapasta commented
@janvanmansum @mderuijter could one of you get the latest from develop (now that 5.8 has been released?)

2021-11-09 07:56 UTC, janvanmansum commented
@scolapasta : done.

2021-11-15 09:01 UTC, janvanmansum commented
@pdurbin @scolapasta : I have merged back the latest `develop` commits to this branch.

2021-11-15 15:30 UTC, merged