Adding -H + API token to curl commands
IQSS/dataverse pull request #7994
Opened 2021-07-08 14:49 UTC by BPeuch

**What this PR does / why we need it**: Without ``-H`` and the API token in these curl commands, the native API rejects the user's requests on the ground that they are a 'guest'.

**Which issue(s) this PR closes**:

Closes #7993

**Additional documentation**: Thanks to Dataverse chat user Lincoln for helping me out with this one!

2021-07-08 16:47 UTC, pdurbin requested changes
@BPeuch thanks for the pull request! It looks great but can you please change these from `$API_KEY` to `$API_TOKEN`? This is for consistency with the rest of the page (and the guide).

2021-07-08 16:47 UTC, pdurbin commented on doc/sphinx-guides/source/api/native-api.rst
> +  curl -H "X-Dataverse-key:$API_KEY" $SERVER_URL/api/datasets/:persistentId/?persistentId=$PERSISTENT_IDENTIFIER
```suggestion
  curl -H "X-Dataverse-key:$API_TOKEN" $SERVER_URL/api/datasets/:persistentId/?persistentId=$PERSISTENT_IDENTIFIER
```

2021-07-08 16:47 UTC, pdurbin commented on doc/sphinx-guides/source/api/native-api.rst
> +  curl -H "X-Dataverse-key:$API_KEY" https://demo.dataverse.org/api/datasets/:persistentId/?persistentId=doi:10.5072/FK2/J8SJZB
```suggestion
  curl -H "X-Dataverse-key:$API_TOKEN" https://demo.dataverse.org/api/datasets/:persistentId/?persistentId=doi:10.5072/FK2/J8SJZB
```

2021-07-08 16:47 UTC, pdurbin commented on doc/sphinx-guides/source/api/native-api.rst
> +  curl -H "X-Dataverse-key:$API_KEY" http://$SERVER/api/datasets/:persistentId/versions/:draft?persistentId=$PERSISTENT_IDENTIFIER
```suggestion
  curl -H "X-Dataverse-key:$API_TOKEN" http://$SERVER/api/datasets/:persistentId/versions/:draft?persistentId=$PERSISTENT_IDENTIFIER
```

2021-07-08 16:47 UTC, pdurbin commented on doc/sphinx-guides/source/api/native-api.rst
> +  curl -H "X-Dataverse-key:$API_KEY" https://demo.dataverse.org/api/datasets/:persistentId/versions/:draft?persistentId=doi:10.5072/FK2/J8SJZB
```suggestion
  curl -H "X-Dataverse-key:$API_TOKEN" https://demo.dataverse.org/api/datasets/:persistentId/versions/:draft?persistentId=doi:10.5072/FK2/J8SJZB
```

2021-07-09 07:32 UTC, BPeuch commented
Thanks for the feedback, Philip!
This is my first time reviewing suggestions here. I think I managed to accept three of them but bungled the fourth one. From where you are, has 'KEY' been replaced with 'TOKEN' in all four occurrences? 🤔

2021-07-09 16:07 UTC, pdurbin approved these changes
Looks good!

2021-07-09 16:08 UTC, pdurbin commented
@BPeuch yes, all set for all four. Thanks!

2021-07-12 07:57 UTC, BPeuch commented
Wonderful! Thanks a lot @pdurbin

2021-07-12 14:34 UTC, merged