#8619 installation prerequisites documentation fixes
IQSS/dataverse pull request #8620
Opened 2022-04-19 16:15 UTC by j-n-c

**What this PR does / why we need it**:

- Downloading Country GeoIP databases from Maxmind now requires having an account
- `sudo yum makecache fast` does not work on RHEL8

**Which issue(s) this PR closes**:

Closes #8619 

**Special notes for your reviewer**:

**Suggestions on how to test this**:

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:

**Is there a release notes update needed for this change?**:

**Additional documentation**:

2022-04-21 14:20 UTC, pdurbin requested changes
There are merge conflicts, probably because PR #8391 tried to address some of this MaxMind/Geolite stuff (#6629).

@j-n-c if you're happy with the MaxMind/Geolite changes above, perhaps you could limit this pull request to just the "makecache" changes. Whatever makes sense. Thanks!

2022-04-22 11:01 UTC, j-n-c commented
@pdurbin limited the changes to the PostgreSQL install with EL8 derivative
Found some typos in https://github.com/IQSS/dataverse/issues/6629. Left fix proposal to @qqmyers in comments section

2022-04-28 19:33 UTC, scolapasta approved these changes
checked with @donsizemore and got the 👍

2022-05-02 14:44 UTC, pdurbin approved these changes
The MaxMind/Geolite changes were removed. Since @donsizemore is happy with the `makecache` stuff (I'm not familiar with it), I'm approving this.

2022-05-02 14:52 UTC, merged