BagIt Support - Improve error messages for BagIt handler
IQSS/dataverse pull request #8792
Opened 2022-06-10 10:38 UTC by adaybujeda

**What this PR does / why we need it**:
Improvements to the error messages for the BagIt file handler. The message location has changed from the top of the page to just underneath the file upload widget.

The message text has been updated following a review from our user testing.

**Which issue(s) this PR closes**:
Closes #8787

**Special notes for your reviewer**:
None

**Suggestions on how to test this**:
As only the error messages has ben updated, we need to enable the `:BagItHandlerEnabled` feature and use invalid BagIt packages.

To enable the feature: curl -X PUT -d 'true' http://localhost:8080/api/admin/settings/:BagItHandlerEnabled

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:
No UI changes. The error messages section where the errors are displayed was already in the system.

**Is there a release notes update needed for this change?**:
No

**Additional documentation**:
None

2022-06-10 10:40 UTC, adaybujeda commented
Sample BagIt packages useful for testing:
[bagit-10-errors.zip](https://github.com/IQSS/dataverse/files/8878151/bagit-10-errors.zip)
[bagit-1-error.zip](https://github.com/IQSS/dataverse/files/8878152/bagit-1-error.zip)
[bagit-no-errors.zip](https://github.com/IQSS/dataverse/files/8878153/bagit-no-errors.zip)

2022-06-10 10:42 UTC, adaybujeda commented
New error location:

<img width="1192" alt="Screenshot 2022-06-10 at 11 22 01" src="https://user-images.githubusercontent.com/17336210/173048656-2d71d175-cd02-4d53-b750-33f15fbd018d.png">

2022-07-19 18:54 UTC, scolapasta requested changes
@adaybujeda overall this looks good - my one comment is that there are several places in the tests that seem to match for specific text. I'm usually not a fan of that because if we decide to change the text for whatever reason the test will fail (when it should not) and it's usually sufficient to just confirm that an error happen (or type of error if that can be gotten from sort of enumerated list).

Could you review the tests and see if there are simplifications to be made so that it doesn't have to rely on matching specific texts?

2022-07-20 08:56 UTC, adaybujeda commented
@scolapasta I have updated the tests that were string matching messages from the `BundleUtil`.
I am now checking that the expected bundle key is used instead.

Let me know if I missed any other tests.

2022-07-20 21:29 UTC, scolapasta approved these changes

2022-07-22 20:48 UTC, merged