Removed fabulousfiletool.com
IQSS/dataverse pull request #8887
Opened 2022-08-03 08:52 UTC by AkiraY1

Removed all references to fabulousfiletool.com on https://guides.dataverse.org/en/latest/api/external-tools.html because fabulousfiletool.com no longer exists. Partial fix for #8874

2022-08-04 20:58 UTC, pdurbin requested changes
@AkiraY1 thanks for the pull request. I assume you want to remove this because fabulousfiletool.com is not a valid website? Really this is just an example so we wouldn't want to remove it. We could replace it with a better example, maybe? With a real website? Not sure. It's probably easiest to leave it alone and close this pull request. I'm happy to hear your thoughts. Thanks again.

2022-08-05 07:46 UTC, AkiraY1 commented
Sure, it makes sense to keep it as an example. Perhaps we could add a short note in parentheses that fabulousfiletool.com no longer exists? I was thinking that someone might try to use fabulousfiletool and assume they're doing something wrong before realizing the whole website is down.

2022-08-05 10:39 UTC, pdurbin commented
Sure, maybe. I don't think fabulousfiletool.com ever existed though. It was just a goofy URL I made up for the example. 😄

2022-08-05 16:15 UTC, AkiraY1 commented
OH hahaha ok then I'll close this PR.

2022-08-05 16:39 UTC, closed without merging