IQSS/8957 JWT creation test for DRS Archiver
IQSS/dataverse pull request #8958
Opened 2022-09-06 21:12 UTC by qqmyers

**What this PR does / why we need it**: Just a simple test created for HDC 3A / Archiving to DRS that didn't make it into the main PR.

**Which issue(s) this PR closes**:

Closes #8957 

**Special notes for your reviewer**:

**Suggestions on how to test this**: Verify the test runs and doesn't fail in the auto build.

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:

**Is there a release notes update needed for this change?**:

**Additional documentation**:

2022-09-07 13:26 UTC, pdurbin requested changes
I'm seeing a failure...

[ERROR] Failures: 

[ERROR]   DRSSubmitToArchiveCommandTest.createJWT:115

... at https://jenkins.dataverse.org/blue/organizations/jenkins/IQSS-Dataverse-Develop-PR/detail/PR-8958/1/pipeline

2022-09-07 14:15 UTC, qqmyers commented
Doesn't https://github.com/IQSS/dataverse/runs/8216433360?check_suite_focus=true#step:5:1132 show it ran and didn't fail?

2022-09-07 15:40 UTC, qqmyers commented
@pdurbin - I don't see any reason it should fail only in jenkins - can a new run be triggered to see if this is repeatable?

2023-02-01 21:38 UTC, scolapasta approved these changes

2023-02-01 23:17 UTC, merged