allow slash in check permissions api request
IQSS/dataverse pull request #8995
Opened 2022-09-26 16:05 UTC by ErykKul

**What this PR does / why we need it**:
It allows using a global identifier, e.g., doi, when checking permissions.

**Which issue(s) this PR closes**:

Closes #8994

2022-11-21 08:41 UTC, ErykKul commented
The workaround here is to first get the dataset with the API, the response contains the technical (DB) ID that can be used (it does not contain slashes, it is an integer) to check the permissions.

2023-09-18 21:09 UTC, qqmyers requested changes
The fix looks like it works for the case where the dataset PID exists, but it will return 500 errors instead of 404  when it isn't found.

2023-09-19 09:05 UTC, ErykKul commented on src/main/java/edu/harvard/iq/dataverse/api/Admin.java
> +				if (dvObj == null) {
I have changed how findDvo works (it returns not null object now, or it throws WrappedResponse as thrown by the findDatasetOrDie). Then I cleaned it up a little bit. I think it is better now.

2023-09-24 20:40 UTC, qqmyers approved these changes

2024-04-04 18:56 UTC, sekmiller commented
Hey @ErykKul, I'd like to pick this up but there's a merge conflict at the moment - so if you could resolve it I'll be able to test. Thanks!

2024-04-04 19:38 UTC, qqmyers commented
Weird - the web editor to resolve the conflict shows 0 conflicts in that file...

2024-04-06 11:26 UTC, ErykKul commented
@sekmiller @qqmyers I see that my PRs moved, but I am on vacation right now for another week, I will be back on 15th. I will re-merge the develop branch to them, do the necessary changes and retest once that I will be back at work. Some of them are open for quite some time, so they need some extra attention from me before merging, Thanks!

2024-04-17 11:20 UTC, ErykKul commented
@sekmiller @qqmyers I had to manually merge the `AbstractApiBean.java`, but there where no conflicts to solve. Strange. It is now merged with the develop branch.

2024-04-17 14:28 UTC, sekmiller commented
Hey @ErykKul This looks great. Thanks! The only thing I need you to do before I can merge it is for you to update the doc so that the url is in double quotes as in  curl -H "X-Dataverse-key:$API_TOKEN" "$SERVER_URL/api/admin/permissions/:persistentId?persistentId=$PERSISTENT_IDENTIFIER" - I would do it myself but I don't think I have permission.

2024-04-19 14:33 UTC, ErykKul commented
@sekmiller Thanks for catching that! I have just added the missing double quotes.

2024-04-22 14:03 UTC, merged