9926: list role assignments permissions
IQSS/dataverse pull request #9956
Opened 2023-09-26 07:19 UTC by vera

**What this PR does / why we need it**:

This fixes the permission inconsistency described in #9926

Listing dataverse role assignments via API still requires ManageDataversePermissions, but listing dataset role assignments via API now requires only the ManageDatasetPermissions.

**Which issue(s) this PR closes**:

Closes #9926

**Special notes for your reviewer**:

/

**Suggestions on how to test this**:

`mvn clean test -Dtest="DatasetsIT#testListRoleAssignments"`

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:

no

**Is there a release notes update needed for this change?**:

yes, might be good

**Additional documentation**:

/

2023-11-10 08:27 UTC, johannes-darms commented
@pdurbin : I was wondering if it would be possible to have a review of this MR.

2023-11-15 13:33 UTC, pdurbin commented
@scolapasta said he'd take a look.

2023-11-29 22:08 UTC, scolapasta requested changes
Looks good, but I left a comment that I hope can remove the need fo rthe contributorPlus role.

2024-01-10 21:04 UTC, scolapasta commented
@vera checking in, were you able to loo at my review comments?

2024-01-11 15:30 UTC, vera commented
@scolapasta sorry, somehow I missed your comment! Will take a look at this asap

2024-01-12 10:37 UTC, vera commented on src/test/java/edu/harvard/iq/dataverse/api/DatasetsIT.java
> +        // We create a new role that includes "ManageDatasetPermissions" which are required for listing role assignments
:+1: done!

2024-01-12 10:38 UTC, vera commented
@scolapasta I removed the new contributorPlus role and used the curator role instead for the test as you suggested.

2024-01-12 19:29 UTC, scolapasta approved these changes

2024-01-12 20:18 UTC, pdurbin commented
@vera hi! Our CI is [failing](https://jenkins.dataverse.org/job/IQSS-Dataverse-Develop-PR/job/PR-9956/3/consoleFull) with this:

`TASK [dataverse : copy warfile over release] ***********************************`
`fatal: [localhost]: FAILED! => {"changed": false, "msg": "Source /opt/dataverse/dataverse/target/dataverse-6.1.war not found"}`

I'll go ahead and merge the latest from develop into your branch to pick up the 6.1 version change.

2024-01-16 16:38 UTC, merged